server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8083/eureka

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: student-service
          uri: lb://STUDENT-SERVICE
          predicates:
            - Path=/student/**
        - id: client-service
          uri: lb://CLIENT-SERVICE
          predicates:
            - Path=/client/**
        - id: university-service
          uri: lb://UNIVERSITY-SERVICE
          predicates:
            - Path=/**
