spring:
  application:
    name: client-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/cgidb?useSSL=false&serverTimezone=UTC
    username: root
    password: root #Replace with your own DB Password

server:
  port: 8086

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  instance:
    hostname: localhost

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 60000
logging:
  level:
    root: info
