spring:
  application:
    name: department-service
  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  datasource:
    url: jdbc:mysql://localhost:3306/cgidb?useSSL=false&serverTimezone=UTC
    username: root
    password: AR7464.cgi #Replace with your own DB Password

server:
  port: 8086

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  instance:
    hostname: localhost
