spring:
  application:
    name: student-service
  data:
    mongodb:
      host: localhost
      port: 27017
      database: BookStore
  main:
    allow-bean-definition-overriding: true


server:
  port: 8085

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8083/eureka/
  instance:
    hostname: localhost

    #instance-id: ${spring.application.name}:${random.value} #added for random


